### ISSUE TITLE
After issuing a color change, following commands fail to do anything.

### ISSUE THREAD

**Issue by thevik** [KsenijaS/krakenx#10] opened 2018-06-24 16:05 UTC
Arch Linux 4.17.2

After a fresh restart, with the LED's of my kraken x62 off:

colctl -m solid -c0 50,0,90  successfully changes the LED's from black to purple

immediately after I run:

colctl -m solid -c0 0,0,0 to change the LED's back to black but nothing happens.

no other colctl commands seem to work until I restart again.

**Comment by willkill07** [comment] 2018-06-25 20:37
I also report the same issue.

kernel version: 4.17.2-1-ARCH
Hardware: Kraken x62

**Comment by jonasmalacofilho** [comment] 2018-07-25 14:05
I can reproduce this as well.

**Comment by jneumaier** [comment] 2018-08-26 21:03
I guess this has been fixed accidentally. Works for me. Please verify.

**Comment by jonasmalacofilho** [comment] 2018-08-27 01:41
I can still reproduce this after a fresh boot, at least on Linux.

Could this maybe be related to detaching the kernel driver but never reattaching it?

**Comment by jneumaier** [comment] 2018-09-05 18:15
Thanks @jonasmalacofilho I merged the pull request #23 but only had time to verify everything works on Windows.
@thevik @willkill07 If you have the time, you are welcome to verfiy the fix on Linux. Otherwise I will just trust jonasmalacofilho's expertise and close the issue in a few days :-)

**Comment by thevik** [comment] 2018-09-05 19:40
Verified on Linux. Thanks for the fix! @jneumaier

**Comment by jneumaier** [comment] 2018-09-05 20:10
@thevik Perfect, thanks!

**Closed by jneumaier** 2018-09-05 20:10 UTC
Labels: bug
